[package]
name = "fluid-wasm"
version = "0.1.0"
authors = ["Moruton"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"

[profile.release]
# Optimize for small size and speed
opt-level = 3
lto = true
